# Generated by Django 5.1.5 on 2025-02-03 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='PostInteractions',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'post_interactions',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('media_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'post_media',
            },
        ),
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
