# Generated by Django 5.1.5 on 2025-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comments_postinteractions_postmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinteractions',
            name='shared_platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postinteractions',
            name='shared_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postinteractions',
            unique_together={('post_id', 'user_id')},
        ),
    ]
