# Generated by Django 5.1.5 on 2025-02-07 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postinteractions_shared_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinteractions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
