# Generated by Django 5.1.5 on 2025-03-17 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postinteractions_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporter_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Content_Reports',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hashtags',
            },
        ),
        migrations.AddField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='community_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('general', 'General'), ('community', 'Community')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('post_hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('hashtag_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_hashtags',
                'unique_together': {('post_id', 'hashtag_id')},
            },
        ),
    ]
