# Generated by Django 5.1.5 on 2025-01-28 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.IntegerField()),
                ('message', models.TextField()),
                ('sender_id', models.IntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='unread', max_length=10)),
            ],
            options={
                'db_table': 'group_chats',
            },
        ),
    ]
