# Generated by Django 5.1.5 on 2025-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_photo_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
        migrations.AddField(
            model_name='community',
            name='photo_community',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/'),
        ),
    ]
