# Generated by Django 5.1.5 on 2025-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_remove_community_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
