# Generated by Django 5.1.5 on 2025-01-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
    ]
