# Generated by Django 5.1.5 on 2025-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_community_photo_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='photo_community',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/'),
        ),
    ]
