# Generated by Django 5.1.5 on 2025-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_communityjoinrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityjoinrequest',
            unique_together={('community_id', 'user_id', 'status')},
        ),
        migrations.AlterField(
            model_name='communityjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='communityjoinrequest',
            table=None,
        ),
        migrations.RemoveField(
            model_name='communityjoinrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='communityjoinrequest',
            name='processed_by',
        ),
    ]
