# Generated by Django 5.1.5 on 2025-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_alter_communityjoinrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityjoinrequest',
            unique_together={('community_id', 'user_id')},
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='processed_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='communityjoinrequest',
            table='Community_Join_Requests',
        ),
    ]
